// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADszcs4yTVG9oBzTwWL8ZV2HaMm7vhqQU',
    appId: '1:210068054832:web:c4b51ccb2e5c033ab35ef5',
    messagingSenderId: '210068054832',
    projectId: 'fooddelivery-ecaa0',
    authDomain: 'fooddelivery-ecaa0.firebaseapp.com',
    storageBucket: 'fooddelivery-ecaa0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHNm-zA2sUt6NRlZCisJZbVXQv1xIGFI8',
    appId: '1:210068054832:android:61eb7396de083b0cb35ef5',
    messagingSenderId: '210068054832',
    projectId: 'fooddelivery-ecaa0',
    storageBucket: 'fooddelivery-ecaa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoOHP7tPgdrX25tmfjMudjkqlz37Q0O94',
    appId: '1:210068054832:ios:f79c71b411083c06b35ef5',
    messagingSenderId: '210068054832',
    projectId: 'fooddelivery-ecaa0',
    storageBucket: 'fooddelivery-ecaa0.appspot.com',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoOHP7tPgdrX25tmfjMudjkqlz37Q0O94',
    appId: '1:210068054832:ios:0f49250503637bd5b35ef5',
    messagingSenderId: '210068054832',
    projectId: 'fooddelivery-ecaa0',
    storageBucket: 'fooddelivery-ecaa0.appspot.com',
    iosBundleId: 'com.example.fooddelivery.RunnerTests',
  );
}
